### PR TITLE
SQL-1271: Fix typo in RELEASE-VERSION vs RELEASE_VERSION

### PR DESCRIPTION
**Pull request by nbagnard**

### CODE REVIEW

**Review by bucaojit — APPROVED** [review]
LGTM!

**Review by jchemburkar — APPROVED** [review]
LGTM!

**Comment by nbagnard** [comment]
I'll try this out on a patch before I merge, just in case because the expansions are different for the S3 task and the shell.exec and the way I export the variables is not RELEASE_VERSION everywhere.

**Comment by nbagnard** [comment]
evergreen merge

**Pull request merged**
