### PR TITLE
SQL-1096: audit to_bit

### PR DESCRIPTION
**Pull request by terakilobyte**
I simplified the string conversion to the same logic as floats since the conversion chart had the same tests.

### CODE REVIEW

**Review by pmeredit — COMMENTED** [review]
Are we not going to give errors if the output buffer isn't large enough?

**Comment by terakilobyte** [comment]
@pmeredit  No need for to_bit, but for `to_binary` and when converting to a string representation

**Review by pmeredit — APPROVED** [review]
LGTM

**Review by nbagnard — APPROVED** [review]
LGTM! Thank you for simplifying the code 👍

**Comment by terakilobyte** [comment]
evergreen merge

**Comment by terakilobyte** [comment]
evergreen merge

**Pull request merged**
