### PR TITLE
SQL-1529: Rust Driver 2.6.0

### PR DESCRIPTION
**Pull request by pmeredit**
Wait to see if the tests pass. I didn't feel like setting up the integration tests locally :joy:

### CODE REVIEW

**Comment by pmeredit** [comment]
Ok, looks like we good

**Review by terakilobyte — APPROVED** [review]
LGTM. Large diff, great work! 🤣

**Comment by pmeredit** [comment]
evergreen merge

**Comment by pmeredit** [comment]
evergreen merge

**Comment by pmeredit** [comment]
evergreen merge

**Pull request merged**
