### PR TITLE
SQL-651: add license file

### PR DESCRIPTION
**Pull request by terakilobyte**
Adding the same license we use for jdbc

### CODE REVIEW

**Review by nbagnard — APPROVED** [review]
LGTM!
No need for license header on files? The Rust driver did not seem to have any, so my guess is that we are fine. Maybe we can check with Alexi again if this is what's expected.

**Comment by terakilobyte** [comment]
evergreen merge

**Comment by terakilobyte** [comment]
evergreen merge

**Comment by pmeredit** [comment]
evergreen merge

**Pull request merged**
