### PR TITLE
SQL_1567: Propagate cursor error 

### PR DESCRIPTION
**Pull request by nbagnard**
Propagate cursor error and don't call deserialize_current on Error or when advance is false because it can panic.

### CODE REVIEW

**Review by pmeredit — APPROVED** [review]
Excellent change, very elegant

**Comment by pmeredit** [comment]
@nbagnard you need to update the `cargo-get` usage like I did in the odbc driver

**Comment by nbagnard** [comment]
> @nbagnard you need to update the `cargo-get` usage like I did in the odbc driver. Also, run `cargo fmt`
> 
> `(cargo get --entry="odbc/Cargo.toml" package.version --major --minor --patch --delimiter=".")`
> 
> Obviously, change the target for the Cargo.toml :)

Ah, very good point. I need to merge the latest changes from master. That should fix it all :D
Thanks for flagging this!

**Review by jchemburkar — APPROVED** [review]
LGTM!

**Comment by nbagnard** [comment]
evergreen merge

**Pull request merged**
