### PR TITLE
SQL-1440: filter out admin and empty strings

### PR DESCRIPTION
**Pull request by terakilobyte**
I've opened a ticket with ADF, and commented the ticket number above the relevant lines I added.

### CODE REVIEW

**Review by bucaojit — CHANGES_REQUESTED** [review]
There's another list_database_names in [fields.rs](https://github.com/mongodb/mongo-odbc-driver/blob/d711fc0b75e81d3e28c573adc6b8be462a44e1eb/core/src/fields.rs#L482) that this filter should be added to.

**Review by bucaojit — APPROVED** [review]
LGTM!

As this will possibly be fixed by ADF soon, we will not worry about adding this as server-side filtering.

**Review by EthanHardyMongo — APPROVED** [review]
LGTM!

**Comment by terakilobyte** [comment]
evergreen merge

**Pull request merged**
